### ISSUE TITLE
New messages do not update in the hub.

### ISSUE THREAD

**Issue by Gh10User** [amonchakai/Hg10#61]
When I receive messages from contacts I currently do not have active conversations in the hub, I must open the application to retrieve them. And, also, the last message visible in the hub is not updated unless I have the application open.

**Comment by amonchakai** [comment]
Yes, currently the refresh of the hub only append when:
- you receive a message while the app is closed (both app and hub)
- you close a conversation in the app to go back to the contact list.

**Comment by Keelan** [comment]
Also having issues with the hub and XMPP. Not conversations appear in the hub. I get a notification noise but no message in the hub or convo to click. Opening the app is this only way to read the message or see who the message is from.

**Comment by amonchakai** [comment]
For your issue, I would just try to reboot the phone. 

If it does not work, try to reinstall the app (and check with 'account cleaner' on BBW that there are no remaining account).

Normally it should work

**Comment by Keelan** [comment]
Hmm i have done all this.

I installed, reinstalled, deleted, rebooted phone, updated hub (top right corner down 5 times)

I edit the name on the contacts filled in all the details. It doesn't change still shows name@xmpp.server.com

**Comment by amonchakai** [comment]
humm... 

just to make sure, the contact are added into the hub when you close the conversation. 
You need the contact to have the field "full name" with something in it.
Then, you open the conversation with that contact
and when you go back to the list of contact, that would be the moment when the hub is updated.

**Comment by amonchakai** [comment]
Ah sorry, do you tap on "set" in the edit contact field?
If it keeps using the email address, the problem is there. I need to have the full name field NOT empty for this contact to be added in the hub.

**Comment by Keelan** [comment]
Ok i got this to work.

Full reinstall -> Opened App -> XMPP Setup -> Edit user -> Change Full Name from name@xmpp.server.com -> Press Set -> Reboot

It showed up but when i opened the message from the hub it was blank and wouldn't mark as read.

Deleted that one, then the next message came through worked. Seems to be ok now.

Is there reason you don't parse anything before the @ as a full name so this worked out of the box?

**Comment by amonchakai** [comment]
I don't think you really had to reboot. I do a lot of test with xmpp, and just editing the name was always sufficient. Anyway, glad it is solved!

And no, it is just for a stupid reason it is like this: I did that in the early stage of the app, when I was mainly looking at hangouts. 
And i saw that between my contacts there was some spam, people I blocked, and they all had in common the fact that the "full name "field was not defined. 

So I thought it was a way to recognize the contacts I don't want, but that was stupid. Google hangouts always define the "full name" for your contacts, but when you are dealing with jabber/xmpp that is another story. 

So I removed this restriction of requiring a full name set, but it is still there in the hub...

**Comment by Keelan** [comment]
@amonchakai 

Ah i see that makes sense.

Another thing:

Get notification via hub, open chat in hub. Receive multiple messages whilst hub chat is open. backout to hub. receive another message from the same conversation. Get no notification. Until you re-open the app.

**Comment by amonchakai** [comment]
yes, so for this, it is due to the fact that I fire a notification only when the card is closed.

The thing, is if you just swipe to close the card. It is not closed immediately.... the OS wait several seconds before closing it, enabling to open the next card more quickly in case you would need to do it... 

So for my app, during this period of time, the card is not closed -> no notification..

However, if you tap on the back button on top left, then I can force the card to close. And you won't have problem with the notification.

**Comment by Keelan** [comment]
That still doesn't work, same behavior as if you swipe or press bottom back button.

If you have the chat open and you receive more than one message and press any 3 of the ways to go back to the hub (bottom left, top left and swipe) You do not receive a notification again until you open the chat up in the app.

You are aware of issues related though, which is good :D

**Comment by amonchakai** [comment]
humm strange...

**Comment by Keelan** [comment]
@amonchakai other than a few little hiccups here and there, great app. The only real xmpp client on BB10, hope to see more improvements. If i was you i would highly consider fixing the little bugs and maybe charge or have pro version. With multi account support and such i'd buy it.

**Comment by amonchakai** [comment]
Many thanks

As for the bugs,  I am planning to fix them. There is still plenty to be done for this app. I will do it at some point. It is just that some things are easier to solve than others.

**Comment by h4ro** [comment]
I tried to add this comment via the app, but after asking if i really want to post (and check for private data and stuff) and pressing yes nothing seems to happen. So I went to the web browser and registered here instead.

I have the same issue with my XMPP account not showing notifications in hub (but sound is playing). I tried to find "XMPP Setup" or "Edit user", but all I can do is put my user and pass in the initial login screen. There is no other option neither logged out nor logged in.
